{
 "title": "DSLStats",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Super Frame Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "superframe_error_count", "legendFormat": "{{link}} : {{direction}}" }
   ]
  },
  {
   "title": "WAN Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(connection_state{connection_state=\"Connected\"}*1) + scalar(connection_state{connection_state=\"Offline\"}*2) + scalar(connection_state{connection_state=\"Down\"}*3)"
    }
   ]
  },
  {
   "title": "DSL Line Uptime",
   "type": "graph",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "link1_uptime", "legendFormat": "Link 1" },
    { "expr": "link2_uptime", "legendFormat": "Link 2" }
   ]
  },
  { "title": "DSL Line Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "HEC Error Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "hec_error_count", "legendFormat": "{{link}} : {{direction}}" }
   ]
  },
  {
   "title": "SN Margin (dB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    { "expr": "sn_margin_db", "legendFormat": "{{link}}: {{direction}}" }
   ]
  },
  {
   "title": "Actual Speed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    { "expr": "download_speed_bps", "legendFormat": "Download" },
    { "expr": "upload_speed_bps", "legendFormat": "Upload Speed" }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "ping_ms", "legendFormat": "Ping (ms)" }
   ]
  },
  {
   "title": "Link Attainable Rate (kbps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "attainable_rate_kbps", "legendFormat": "{{link}}: {{direction}}" }
   ]
  },
  {
   "title": "RS Correctable Error Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "rs_correctable_error_count", "legendFormat": "{{link}} : {{direction}}" }
   ]
  },
  {
   "title": "Total Errors (Seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "total_err_seconds", "legendFormat": "{{link}} : {{direction}}" }
   ]
  },
  {
   "title": "RS Uncorrectable Error Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "rs_uncorrectable_error_count", "legendFormat": "{{link}} : {{direction}}" }
   ]
  },
  { "title": "Weather Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Precipitation Intensity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "outdoor_precipitation_intensity",
     "legendFormat": "Precipitation Intensity"
    }
   ]
  },
  {
   "title": "Cloud Coverage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "outdoor_cloud_cover_pct" }
   ]
  },
  {
   "title": "Outdoor Temp (℉)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    { "expr": "outdoor_temperature_f" }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "targets": [
    { "expr": "outdoor_wind_speed_mph", "legendFormat": "Speed" },
    { "expr": "outdoor_wind_gust_mph", "legendFormat": "Gusts" }
   ]
  }
 ]
}