global:
  scrape_interval:     1m
  evaluation_interval: 1m
  scrape_timeout:      10s

scrape_configs:
  - job_name: 'dsl'
    scrape_interval: 5s
    scrape_timeout:  5s
    static_configs:
      - targets: ['dsl_exporter:8001']
  - job_name: 'speedtest'
    metrics_path: /probe
    scrape_interval: 10m
    scrape_timeout: 120s
    static_configs:
      - targets: [ 'speedtest_exporter:9516' ]
  - job_name: 'weather'
    scrape_interval: 1m
    scrape_timeout:  30s
    static_configs:
      - targets: ['weather_exporter:8000']